name: Release

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Set up ssh agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.RELEASE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.10'

      - name: Install BrewKit
        run: go install github.com/ispringtech/brewkit/cmd/brewkit@v1.0.0

      - name: Build
        run: brewkit build
